load doorkeeper
load doorkeeper first, or will raise `undefined method `configure' for Doorkeeper:Module (NoMethodError)`

because in dev env, `doorkeeper` is added in `Gemfile`, so bundler will help to require it, but `Readme` said just add `doorkeeper-mongodb` into `Gemfile` so bundler will not automatic require `doorkeeper`